const USER_REVIEW_ACTION_TYPES = {
  ADD_USER_REVIEWS: "ADD_USER_REVIEWS",
  ADD_USER_REVIEW: "ADD_USER_REVIEW",
  UPDATE_USER_REVIEW: "UPDATE_USER_REVIEW",
  DELETE_USER_REVIEW: "DELETE_USER_REVIEW",
  CLEAR_USER_REVIEWS: "CLEAR_USER_REVIEWS",
};

export default USER_REVIEW_ACTION_TYPES;