const WISHLIST_ACTION_TYPES = {
  ADD_WISHLISTS: "ADD_WISHLISTS",
  ADD_WISHLIST: "ADD_WISHLIST",
  REMOVE_WISHLIST: "REMOVE_WISHLIST",
  RESET_WISHLISTS: "RESET_WISHLISTS",
};

export default WISHLIST_ACTION_TYPES;