const REVIEW_ACTION_TYPES = {
  ADD_REVIEWS: "ADD_REVIEWS",
  ADD_REVIEW: "ADD_REVIEW",
  UPDATE_REVIEW: "UPDATE_REVIEW",
  DELETE_REVIEW: "DELETE_REVIEW",
  CLEAR_REVIEWS: "CLEAR_REVIEWS",
};

export default REVIEW_ACTION_TYPES;