const ORDER_LIST_ACTION_TYPES = {
  ADD_ORDERS: "ADD_ORDERS",
  ADD_ORDER: "ADD_ORDER",
  UPDATE_ORDER: "UPDATE_ORDER",
  DELETE_ORDER: "DELETE_ORDER",
  CLEAR_ORDERS: "CLEAR_ORDERS",
};

export default ORDER_LIST_ACTION_TYPES;